// DO NOT EDIT: File is generated by code generator.
using System.Text.Json.Serialization;

namespace PokepayPartnerCsharpSdk.Response
{
    public class PrivateMoneySummary
    {
        public double TopupAmount { get; }
        public double RefundedTopupAmount { get; }
        public double PaymentAmount { get; }
        public double RefundedPaymentAmount { get; }
        public double AddedPointAmount { get; }
        public double RefundedAddedPointAmount { get; }
        public double ExchangeInflowAmount { get; }
        public double ExchangeOutflowAmount { get; }
        public int TransactionCount { get; }

        [JsonConstructor]
        public PrivateMoneySummary(double topupAmount, double refundedTopupAmount, double paymentAmount, double refundedPaymentAmount, double addedPointAmount, double refundedAddedPointAmount, double exchangeInflowAmount, double exchangeOutflowAmount, int transactionCount) =>
            (TopupAmount, RefundedTopupAmount, PaymentAmount, RefundedPaymentAmount, AddedPointAmount, RefundedAddedPointAmount, ExchangeInflowAmount, ExchangeOutflowAmount, TransactionCount) = (topupAmount, refundedTopupAmount, paymentAmount, refundedPaymentAmount, addedPointAmount, refundedAddedPointAmount, exchangeInflowAmount, exchangeOutflowAmount, transactionCount);
    }
}
