// DO NOT EDIT: File is generated by code generator.
using System.Text.Json.Serialization;

namespace PokepayPartnerCsharpSdk.Response
{
    public class UserStatsOperation
    {
        public string Id { get; }
        public string From { get; }
        public string To { get; }
        public string Status { get; }
        public string ErrorReason { get; }
        public string DoneAt { get; }
        public string FileUrl { get; }
        public string RequestedAt { get; }

        [JsonConstructor]
        public UserStatsOperation(string id, string from, string to, string status, string requestedAt) =>
            (Id, From, To, Status, RequestedAt) = (id, from, to, status, requestedAt);
    }
}
