// DO NOT EDIT: File is generated by code generator.
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

using PokepayPartnerCsharpSdk;
using PokepayPartnerCsharpSdk.Response;

namespace PokepayPartnerCsharpSdk.Request
{
    public class CreateTransactionGroup
    {
#if NETFRAMEWORK
        public string Name { get; set; }
#else
        public string Name { get; set; }
#endif

        public CreateTransactionGroup(string name) =>
            (Name) = (name);

        private string path { get { return "/transaction-groups"; } }

        private static readonly HttpMethod method = new HttpMethod("POST");

#if NETFRAMEWORK
        public async Task<TransactionGroup> Send(Client client) {
                string res = await client.Send(path, CreateTransactionGroup.method, this);
                return JsonSerializer.Deserialize<TransactionGroup>(res, client.JsonOptions);
        }
#else
#nullable enable
        public async Task<TransactionGroup?> Send(Client client) {
                string res = await client.Send(path, CreateTransactionGroup.method, this);
                return JsonSerializer.Deserialize<TransactionGroup>(res, client.JsonOptions);
        }
#endif
    }
}
