// DO NOT EDIT: File is generated by code generator.
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

using PokepayPartnerCsharpSdk;
using PokepayPartnerCsharpSdk.Response;

namespace PokepayPartnerCsharpSdk.Request
{
    public class CreateShop
    {
#if NETFRAMEWORK
        public string ShopName { get; set; }
        public string ShopPostalCode { get; set; }
        public string ShopAddress { get; set; }
        public string ShopTel { get; set; }
        public string ShopEmail { get; set; }
        public string ShopExternalId { get; set; }
        public string OrganizationCode { get; set; }
#else
        public string ShopName { get; set; }
        #nullable enable
        public string? ShopPostalCode { get; set; }
        #nullable enable
        public string? ShopAddress { get; set; }
        #nullable enable
        public string? ShopTel { get; set; }
        #nullable enable
        public string? ShopEmail { get; set; }
        #nullable enable
        public string? ShopExternalId { get; set; }
        #nullable enable
        public string? OrganizationCode { get; set; }
#endif

        public CreateShop(string shopName) =>
            (ShopName) = (shopName);

        private string path { get { return "/shops"; } }

        private static readonly HttpMethod method = new HttpMethod("POST");

#if NETFRAMEWORK
        public async Task<User> Send(Client client) {
                string res = await client.Send(path, CreateShop.method, this);
                return JsonSerializer.Deserialize<User>(res, client.JsonOptions);
        }
#else
#nullable enable
        public async Task<User?> Send(Client client) {
                string res = await client.Send(path, CreateShop.method, this);
                return JsonSerializer.Deserialize<User>(res, client.JsonOptions);
        }
#endif
    }
}
