// DO NOT EDIT: File is generated by code generator.
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

using PokepayPartnerCsharpSdk;
using PokepayPartnerCsharpSdk.Response;

namespace PokepayPartnerCsharpSdk.Request
{
    public class CreateShopV2
    {
        public string Name { get; set; }
        #nullable enable
        public string? PostalCode { get; set; }
        #nullable enable
        public string? Address { get; set; }
        #nullable enable
        public string? Tel { get; set; }
        #nullable enable
        public string? Email { get; set; }
        #nullable enable
        public string? ExternalId { get; set; }
        #nullable enable
        public string? OrganizationCode { get; set; }
        #nullable enable
        public string[]? PrivateMoneyIds { get; set; }
        #nullable enable
        public string[]? CanTopupPrivateMoneyIds { get; set; }

        public CreateShopV2(string name) =>
            (Name) = (name);

        private string path { get { return "/shops-v2"; } }

        private static readonly HttpMethod method = new HttpMethod("POST");

        #nullable enable
        public async Task<ShopWithAccounts?> Send(Client client) {
            string res = await client.Send(path, CreateShopV2.method, this);
            return JsonSerializer.Deserialize<ShopWithAccounts>(res, client.JsonOptions);
        }
    }
}
