// DO NOT EDIT: File is generated by code generator.
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

using PokepayPartnerCsharpSdk;
using PokepayPartnerCsharpSdk.Response;

namespace PokepayPartnerCsharpSdk.Request
{
    public class GetCustomerCards
    {
        private string CustomerId { get; set; }
#if NETFRAMEWORK
        public System.Nullable<int> Page { get; set; }
        public System.Nullable<int> PerPage { get; set; }
#else
        #nullable enable
        public int? Page { get; set; }
        #nullable enable
        public int? PerPage { get; set; }
#endif

        public GetCustomerCards(string customerId) =>
            (CustomerId) = (customerId);

        private string path { get { return "/customers" + "/" + CustomerId + "/cards"; } }

        private static readonly HttpMethod method = new HttpMethod("GET");

#if NETFRAMEWORK
        public async Task<PaginatedUserCards> Send(Client client) {
                string res = await client.Send(path, GetCustomerCards.method, this);
                return JsonSerializer.Deserialize<PaginatedUserCards>(res, client.JsonOptions);
        }
#else
#nullable enable
        public async Task<PaginatedUserCards?> Send(Client client) {
                string res = await client.Send(path, GetCustomerCards.method, this);
                return JsonSerializer.Deserialize<PaginatedUserCards>(res, client.JsonOptions);
        }
#endif
    }
}
