// DO NOT EDIT: File is generated by code generator.
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

using PokepayPartnerCsharpSdk;
using PokepayPartnerCsharpSdk.Response;

namespace PokepayPartnerCsharpSdk.Request
{
    public class ListOrganizations
    {
#if NETFRAMEWORK
        public string PrivateMoneyId { get; set; }
        public System.Nullable<int> Page { get; set; }
        public System.Nullable<int> PerPage { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
#else
        public string PrivateMoneyId { get; set; }
        #nullable enable
        public int? Page { get; set; }
        #nullable enable
        public int? PerPage { get; set; }
        #nullable enable
        public string? Name { get; set; }
        #nullable enable
        public string? Code { get; set; }
#endif

        public ListOrganizations(string privateMoneyId) =>
            (PrivateMoneyId) = (privateMoneyId);

        private string path { get { return "/organizations"; } }

        private static readonly HttpMethod method = new HttpMethod("GET");

#if NETFRAMEWORK
        public async Task<PaginatedOrganizations> Send(Client client) {
                string res = await client.Send(path, ListOrganizations.method, this);
                return JsonSerializer.Deserialize<PaginatedOrganizations>(res, client.JsonOptions);
        }
#else
#nullable enable
        public async Task<PaginatedOrganizations?> Send(Client client) {
                string res = await client.Send(path, ListOrganizations.method, this);
                return JsonSerializer.Deserialize<PaginatedOrganizations>(res, client.JsonOptions);
        }
#endif
    }
}
