// DO NOT EDIT: File is generated by code generator.
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

using PokepayPartnerCsharpSdk;
using PokepayPartnerCsharpSdk.Response;

namespace PokepayPartnerCsharpSdk.Request
{
    public class ListUserAccounts
    {
        private string UserId { get; set; }
        public int Page { get; set; }
        public int PerPage { get; set; }

        public ListUserAccounts(string userId) =>
            (UserId) = (userId);

        private string path { get { return "/users" + "/" + UserId + "/accounts"; } }

        private static readonly HttpMethod method = new HttpMethod("GET");

        public async Task<PaginatedAccountDetails> Send(Client client) {
            string res = await client.Send(path, ListUserAccounts.method, this);
            return JsonSerializer.Deserialize<PaginatedAccountDetails>(res, client.JsonOptions);
        }
    }
}
