// DO NOT EDIT: File is generated by code generator.
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

using PokepayPartnerCsharpSdk;
using PokepayPartnerCsharpSdk.Response;

namespace PokepayPartnerCsharpSdk.Request
{
    public class RefundTransaction
    {
        private string TransactionId { get; set; }
#if NETFRAMEWORK
        public string Description { get; set; }
        public string ReturningPointExpiresAt { get; set; }
#else
        #nullable enable
        public string? Description { get; set; }
        #nullable enable
        public string? ReturningPointExpiresAt { get; set; }
#endif

        public RefundTransaction(string transactionId) =>
            (TransactionId) = (transactionId);

        private string path { get { return "/transactions" + "/" + TransactionId + "/refund"; } }

        private static readonly HttpMethod method = new HttpMethod("POST");

#if NETFRAMEWORK
        public async Task<TransactionDetail> Send(Client client) {
                string res = await client.Send(path, RefundTransaction.method, this);
                return JsonSerializer.Deserialize<TransactionDetail>(res, client.JsonOptions);
        }
#else
#nullable enable
        public async Task<TransactionDetail?> Send(Client client) {
                string res = await client.Send(path, RefundTransaction.method, this);
                return JsonSerializer.Deserialize<TransactionDetail>(res, client.JsonOptions);
        }
#endif
    }
}
