// DO NOT EDIT: File is generated by code generator.
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

using PokepayPartnerCsharpSdk;
using PokepayPartnerCsharpSdk.Response;

namespace PokepayPartnerCsharpSdk.Request
{
    public class RefundExternalTransaction
    {
        private string EventId { get; set; }
#if NETFRAMEWORK
        public string Description { get; set; }
#else
        #nullable enable
        public string? Description { get; set; }
#endif

        public RefundExternalTransaction(string eventId) =>
            (EventId) = (eventId);

        private string path { get { return "/external-transactions" + "/" + EventId + "/refund"; } }

        private static readonly HttpMethod method = new HttpMethod("POST");

#if NETFRAMEWORK
        public async Task<ExternalTransaction> Send(Client client) {
                string res = await client.Send(path, RefundExternalTransaction.method, this);
                return JsonSerializer.Deserialize<ExternalTransaction>(res, client.JsonOptions);
        }
#else
#nullable enable
        public async Task<ExternalTransaction?> Send(Client client) {
                string res = await client.Send(path, RefundExternalTransaction.method, this);
                return JsonSerializer.Deserialize<ExternalTransaction>(res, client.JsonOptions);
        }
#endif
    }
}
