// DO NOT EDIT: File is generated by code generator.
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

using PokepayPartnerCsharpSdk;
using PokepayPartnerCsharpSdk.Response;

namespace PokepayPartnerCsharpSdk.Request
{
    public class ResumeBulkTransaction
    {
        private string BulkTransactionId { get; set; }
#if NETFRAMEWORK
#else
#endif

        public ResumeBulkTransaction(string bulkTransactionId) =>
            (BulkTransactionId) = (bulkTransactionId);

        private string path { get { return "/bulk-transactions" + "/" + BulkTransactionId + "/resume"; } }

        private static readonly HttpMethod method = new HttpMethod("POST");

#if NETFRAMEWORK
        public async Task<BulkTransaction> Send(Client client) {
                string res = await client.Send(path, ResumeBulkTransaction.method, this);
                return JsonSerializer.Deserialize<BulkTransaction>(res, client.JsonOptions);
        }
#else
#nullable enable
        public async Task<BulkTransaction?> Send(Client client) {
                string res = await client.Send(path, ResumeBulkTransaction.method, this);
                return JsonSerializer.Deserialize<BulkTransaction>(res, client.JsonOptions);
        }
#endif
    }
}
