// DO NOT EDIT: File is generated by code generator.
using System;
using System.Net;
using System.Net.Http;
using NUnit.Framework;
using System.Threading.Tasks;
using System.Collections.Generic;

using PokepayPartnerCsharpSdk;

namespace PokepayPartnerCsharpSdk.Test
{
    public class TestGetShopAccounts
    {
        private Client client;

        [OneTimeSetUp]
        public void OneTimeSetup()
        {
            client = new Client("~/.pokepay/test-config.ini");
        }

        [Test]
        public async Task GetShopAccounts0()
        {
            try {
                Request.GetShopAccounts request = new Request.GetShopAccounts(
                    "122f7c99-ba73-409e-bcaf-ca2e6fa9d12e"
                );
                Response.PaginatedAccountWithUsers response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task GetShopAccounts1()
        {
            try {
                Request.GetShopAccounts request = new Request.GetShopAccounts(
                    "122f7c99-ba73-409e-bcaf-ca2e6fa9d12e"
                ) {
                    IsSuspended = true,
                };
                Response.PaginatedAccountWithUsers response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task GetShopAccounts2()
        {
            try {
                Request.GetShopAccounts request = new Request.GetShopAccounts(
                    "122f7c99-ba73-409e-bcaf-ca2e6fa9d12e"
                ) {
                    CreatedAtTo = "2022-08-14T03:51:44.000000+09:00",
                    IsSuspended = true,
                };
                Response.PaginatedAccountWithUsers response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task GetShopAccounts3()
        {
            try {
                Request.GetShopAccounts request = new Request.GetShopAccounts(
                    "122f7c99-ba73-409e-bcaf-ca2e6fa9d12e"
                ) {
                    CreatedAtFrom = "2019-11-10T12:31:26.000000+09:00",
                    CreatedAtTo = "2019-03-02T06:47:02.000000+09:00",
                    IsSuspended = false,
                };
                Response.PaginatedAccountWithUsers response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task GetShopAccounts4()
        {
            try {
                Request.GetShopAccounts request = new Request.GetShopAccounts(
                    "122f7c99-ba73-409e-bcaf-ca2e6fa9d12e"
                ) {
                    PerPage = 5016,
                    CreatedAtFrom = "2021-02-21T01:26:31.000000+09:00",
                    CreatedAtTo = "2021-11-11T09:43:58.000000+09:00",
                    IsSuspended = false,
                };
                Response.PaginatedAccountWithUsers response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task GetShopAccounts5()
        {
            try {
                Request.GetShopAccounts request = new Request.GetShopAccounts(
                    "122f7c99-ba73-409e-bcaf-ca2e6fa9d12e"
                ) {
                    Page = 878,
                    PerPage = 4128,
                    CreatedAtFrom = "2016-03-21T11:12:51.000000+09:00",
                    CreatedAtTo = "2023-10-10T08:53:50.000000+09:00",
                    IsSuspended = true,
                };
                Response.PaginatedAccountWithUsers response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

    }
}
