// DO NOT EDIT: File is generated by code generator.
#nullable enable
using System;
using System.Net;
using System.Net.Http;
using NUnit.Framework;
using System.Threading.Tasks;

using PokepayPartnerCsharpSdk;

namespace PokepayPartnerCsharpSdk.Test
{
    public class TestCreateCashtray
    {
        private Client? client;

        [OneTimeSetUp]
        public void OneTimeSetup()
        {
            client = new Client("~/.pokepay/test-config.ini");
        }

        [Test]
        public async Task CreateCashtray0()
        {
            try {
                Request.CreateCashtray request = new Request.CreateCashtray(
                    "dfc5a242-9910-4e02-8acf-8107b715e8eb",
                    "852fd018-fd23-481b-9cc4-a333ad15e046",
                    8463
                );
                Response.Cashtray response = await request.Send(client!);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.StatusCode!, (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.StatusCode >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task CreateCashtray1()
        {
            try {
                Request.CreateCashtray request = new Request.CreateCashtray(
                    "dfc5a242-9910-4e02-8acf-8107b715e8eb",
                    "852fd018-fd23-481b-9cc4-a333ad15e046",
                    8463
                ) {
                    ExpiresIn = 1911,
                };
                Response.Cashtray response = await request.Send(client!);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.StatusCode!, (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.StatusCode >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task CreateCashtray2()
        {
            try {
                Request.CreateCashtray request = new Request.CreateCashtray(
                    "dfc5a242-9910-4e02-8acf-8107b715e8eb",
                    "852fd018-fd23-481b-9cc4-a333ad15e046",
                    8463
                ) {
                    Description = "naI0WeOGlWmmegc1KGhe3TxnuKac7CS1DK4Gnrr3oBLGMXHrz9mqfRhRmUp8pN9pjtBKEK15Dd3XxCT0Zmu6u7tOxquneNatGolCf6SjeF7SeZXyMS6WkNJ2",
                    ExpiresIn = 2760,
                };
                Response.Cashtray response = await request.Send(client!);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.StatusCode!, (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.StatusCode >= 300, "Should be larger than 300");
            }
        }

    }
}
