// DO NOT EDIT: File is generated by code generator.
using System;
using System.Net;
using System.Net.Http;
using NUnit.Framework;
using System.Threading.Tasks;
using System.Collections.Generic;

using PokepayPartnerCsharpSdk;

namespace PokepayPartnerCsharpSdk.Test
{
    public class TestUpdateAccount
    {
        private Client client;

        [OneTimeSetUp]
        public void OneTimeSetup()
        {
            client = new Client("~/.pokepay/test-config.ini");
        }

        [Test]
        public async Task UpdateAccount0()
        {
            try {
                Request.UpdateAccount request = new Request.UpdateAccount(
                    "f687016b-d0b3-46f2-8833-e8985291851f"
                );
                Response.AccountDetail response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task UpdateAccount1()
        {
            try {
                Request.UpdateAccount request = new Request.UpdateAccount(
                    "f687016b-d0b3-46f2-8833-e8985291851f"
                ) {
                    CanTransferTopup = true,
                };
                Response.AccountDetail response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task UpdateAccount2()
        {
            try {
                Request.UpdateAccount request = new Request.UpdateAccount(
                    "f687016b-d0b3-46f2-8833-e8985291851f"
                ) {
                    Status = "pre-closed",
                    CanTransferTopup = true,
                };
                Response.AccountDetail response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task UpdateAccount3()
        {
            try {
                Request.UpdateAccount request = new Request.UpdateAccount(
                    "f687016b-d0b3-46f2-8833-e8985291851f"
                ) {
                    IsSuspended = true,
                    Status = "active",
                    CanTransferTopup = false,
                };
                Response.AccountDetail response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

    }
}
