// DO NOT EDIT: File is generated by code generator.
using System;
using System.Net;
using System.Net.Http;
using NUnit.Framework;
using System.Threading.Tasks;
using System.Collections.Generic;

using PokepayPartnerCsharpSdk;

namespace PokepayPartnerCsharpSdk.Test
{
    public class TestUpdateCheck
    {
        private Client client;

        [OneTimeSetUp]
        public void OneTimeSetup()
        {
            client = new Client("~/.pokepay/test-config.ini");
        }

        [Test]
        public async Task UpdateCheck0()
        {
            try {
                Request.UpdateCheck request = new Request.UpdateCheck(
                    "40ac8f20-6f58-4b05-8ea2-47453736b61d"
                );
                Response.Check response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task UpdateCheck1()
        {
            try {
                Request.UpdateCheck request = new Request.UpdateCheck(
                    "40ac8f20-6f58-4b05-8ea2-47453736b61d"
                ) {
                    IsDisabled = true,
                };
                Response.Check response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task UpdateCheck2()
        {
            try {
                Request.UpdateCheck request = new Request.UpdateCheck(
                    "40ac8f20-6f58-4b05-8ea2-47453736b61d"
                ) {
                    BearPointAccount = "b48c03c2-eac4-452c-a520-a97f9a6f36e2",
                    IsDisabled = false,
                };
                Response.Check response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task UpdateCheck3()
        {
            try {
                Request.UpdateCheck request = new Request.UpdateCheck(
                    "40ac8f20-6f58-4b05-8ea2-47453736b61d"
                ) {
                    PointExpiresInDays = 6611,
                    BearPointAccount = "2f4460cf-a0eb-4549-b58b-1889f4093836",
                    IsDisabled = true,
                };
                Response.Check response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task UpdateCheck4()
        {
            try {
                Request.UpdateCheck request = new Request.UpdateCheck(
                    "40ac8f20-6f58-4b05-8ea2-47453736b61d"
                ) {
                    PointExpiresAt = "2024-10-08T05:56:30.000000Z",
                    PointExpiresInDays = 6778,
                    BearPointAccount = "9f3cfdee-4501-499c-bdb3-681527ec2896",
                    IsDisabled = false,
                };
                Response.Check response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task UpdateCheck5()
        {
            try {
                Request.UpdateCheck request = new Request.UpdateCheck(
                    "40ac8f20-6f58-4b05-8ea2-47453736b61d"
                ) {
                    StartsAt = "2025-07-20T17:54:04.000000Z",
                    PointExpiresAt = "2020-07-22T22:28:29.000000Z",
                    PointExpiresInDays = 7543,
                    BearPointAccount = "b3a15941-5b64-4d67-b2d7-b62cf2add97a",
                    IsDisabled = true,
                };
                Response.Check response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task UpdateCheck6()
        {
            try {
                Request.UpdateCheck request = new Request.UpdateCheck(
                    "40ac8f20-6f58-4b05-8ea2-47453736b61d"
                ) {
                    ExpiresAt = "2024-11-13T18:36:24.000000Z",
                    StartsAt = "2024-01-05T14:54:46.000000Z",
                    PointExpiresAt = "2023-04-12T11:00:51.000000Z",
                    PointExpiresInDays = 5802,
                    BearPointAccount = "7cd04551-ad13-48be-a604-b282be1a6906",
                    IsDisabled = true,
                };
                Response.Check response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task UpdateCheck7()
        {
            try {
                Request.UpdateCheck request = new Request.UpdateCheck(
                    "40ac8f20-6f58-4b05-8ea2-47453736b61d"
                ) {
                    UsageLimit = 9387,
                    ExpiresAt = "2023-03-05T04:38:58.000000Z",
                    StartsAt = "2025-11-24T11:38:51.000000Z",
                    PointExpiresAt = "2021-02-14T03:06:19.000000Z",
                    PointExpiresInDays = 7723,
                    BearPointAccount = "9dff3256-e382-4be8-8324-7e59d5f1fa6d",
                    IsDisabled = false,
                };
                Response.Check response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task UpdateCheck8()
        {
            try {
                Request.UpdateCheck request = new Request.UpdateCheck(
                    "40ac8f20-6f58-4b05-8ea2-47453736b61d"
                ) {
                    IsOnetime = false,
                    UsageLimit = 6059,
                    ExpiresAt = "2024-12-18T05:21:13.000000Z",
                    StartsAt = "2026-01-30T04:00:33.000000Z",
                    PointExpiresAt = "2024-03-19T23:10:21.000000Z",
                    PointExpiresInDays = 9482,
                    BearPointAccount = "011991c0-2a47-485c-b4a4-419d60480979",
                    IsDisabled = false,
                };
                Response.Check response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task UpdateCheck9()
        {
            try {
                Request.UpdateCheck request = new Request.UpdateCheck(
                    "40ac8f20-6f58-4b05-8ea2-47453736b61d"
                ) {
                    Description = "iVBFtaHsVEu5jHLt1IIKsQ450xUM6O5hfI4vi32RsgmtpDzruBR2bpCJbWCsF1XOMwOMfbCbRi8MeoObjQBbD5vivOmPF0WWyAe43BTjYiVtdGDmgs4Vk2VUx2tI5N4bIOpNtWwRJ7taF",
                    IsOnetime = false,
                    UsageLimit = 591,
                    ExpiresAt = "2022-02-27T19:34:39.000000Z",
                    StartsAt = "2023-07-24T18:41:34.000000Z",
                    PointExpiresAt = "2020-03-21T18:53:11.000000Z",
                    PointExpiresInDays = 8838,
                    BearPointAccount = "fa82d6ff-dfaa-4bdc-a898-adcecf8f937c",
                    IsDisabled = true,
                };
                Response.Check response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task UpdateCheck10()
        {
            try {
                Request.UpdateCheck request = new Request.UpdateCheck(
                    "40ac8f20-6f58-4b05-8ea2-47453736b61d"
                ) {
                    PointAmount = 6201.0,
                    Description = "omkOYYX",
                    IsOnetime = false,
                    UsageLimit = 4657,
                    ExpiresAt = "2022-09-11T10:15:22.000000Z",
                    StartsAt = "2024-10-03T07:04:01.000000Z",
                    PointExpiresAt = "2024-08-01T05:36:35.000000Z",
                    PointExpiresInDays = 5442,
                    BearPointAccount = "49088d2b-732b-49a4-952c-4422dd17bced",
                    IsDisabled = true,
                };
                Response.Check response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task UpdateCheck11()
        {
            try {
                Request.UpdateCheck request = new Request.UpdateCheck(
                    "40ac8f20-6f58-4b05-8ea2-47453736b61d"
                ) {
                    MoneyAmount = 325.0,
                    PointAmount = 9913.0,
                    Description = "WtANH45sfx8Sg9q1O62IQSAJ63xgskw6yfFQPcXHRn98CcSXK5Zlq5PBZ9vRV0xbdBDEvdzHS5KI84n4B4JwtxMbsrynFzleqVzZvPQrwaZ5xfzumz05DAlrcpNez8TuusjLCXuqGq9aXt2RyxOmHZB8Yd9TYL0bkCAVqSRIdac4BtBwC2bbOKrqEvtHSmLf6gZqS",
                    IsOnetime = true,
                    UsageLimit = 6498,
                    ExpiresAt = "2025-09-13T01:49:38.000000Z",
                    StartsAt = "2022-10-21T00:39:40.000000Z",
                    PointExpiresAt = "2024-09-18T01:25:06.000000Z",
                    PointExpiresInDays = 1169,
                    BearPointAccount = "088c8e35-64dd-4428-bd3c-0635dcc768d2",
                    IsDisabled = false,
                };
                Response.Check response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

    }
}
