// DO NOT EDIT: File is generated by code generator.
using System;
using System.Net;
using System.Net.Http;
using NUnit.Framework;
using System.Threading.Tasks;
using System.Collections.Generic;

using PokepayPartnerCsharpSdk;

namespace PokepayPartnerCsharpSdk.Test
{
    public class TestCreateBankTopupTransaction
    {
        private Client client;

        [OneTimeSetUp]
        public void OneTimeSetup()
        {
            client = new Client("~/.pokepay/test-config.ini");
        }

        [Test]
        public async Task CreateBankTopupTransaction0()
        {
            try {
                Request.CreateBankTopupTransaction request = new Request.CreateBankTopupTransaction(
                    "d5ad334e-9489-4b31-b1a5-bde4851ff77f",
                    "02e1a069-d9a4-4c54-8950-1f19d585254d",
                    9384,
                    "2b325e79-2bfc-47a3-a61c-658a3c1808ec",
                    "87b8caaf-ed24-47d0-b738-fbd858d3214a"
                );
                Response.TransactionDetail response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

    }
}
