// DO NOT EDIT: File is generated by code generator.
using System;
using System.Net;
using System.Net.Http;
using NUnit.Framework;
using System.Threading.Tasks;
using System.Collections.Generic;

using PokepayPartnerCsharpSdk;

namespace PokepayPartnerCsharpSdk.Test
{
    public class TestCreateTopupTransactionWithCheck
    {
        private Client client;

        [OneTimeSetUp]
        public void OneTimeSetup()
        {
            client = new Client("~/.pokepay/test-config.ini");
        }

        [Test]
        public async Task CreateTopupTransactionWithCheck0()
        {
            try {
                Request.CreateTopupTransactionWithCheck request = new Request.CreateTopupTransactionWithCheck(
                    "868e5c11-4cc4-49bc-85fa-63810b85da65",
                    "3918ac9a-e7ee-40b9-9e25-c17d02968c56"
                );
                Response.TransactionDetail response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task CreateTopupTransactionWithCheck1()
        {
            try {
                Request.CreateTopupTransactionWithCheck request = new Request.CreateTopupTransactionWithCheck(
                    "868e5c11-4cc4-49bc-85fa-63810b85da65",
                    "3918ac9a-e7ee-40b9-9e25-c17d02968c56"
                ) {
                    RequestId = "d58acfa1-dd8e-4945-8d68-d739993bb8bc",
                };
                Response.TransactionDetail response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

    }
}
