// DO NOT EDIT: File is generated by code generator.
using System;
using System.Net;
using System.Net.Http;
using NUnit.Framework;
using System.Threading.Tasks;

using PokepayPartnerCsharpSdk;

namespace PokepayPartnerCsharpSdk.Test
{
    public class TestBulkCreateTransaction
    {
        private Client client;

        [OneTimeSetUp]
        public void OneTimeSetup()
        {
            client = new Client("~/.pokepay/test-config.ini");
        }

        [Test]
        public async Task BulkCreateTransaction0()
        {
            try {
                Request.BulkCreateTransaction request = new Request.BulkCreateTransaction(
                    "CAyi0eUz4xXH5OLhVoB1lIuiO",
                    "fxpiSD0",
                    "ualUMr1aiXbRr0Yt6Ont0eqhymEV4KDx3FmD"
                );
                Response.BulkTransaction response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task BulkCreateTransaction1()
        {
            try {
                Request.BulkCreateTransaction request = new Request.BulkCreateTransaction(
                    "CAyi0eUz4xXH5OLhVoB1lIuiO",
                    "fxpiSD0",
                    "ualUMr1aiXbRr0Yt6Ont0eqhymEV4KDx3FmD"
                ) {
                    Description = "9kbbli1vOnH69EFivIjA6",
                };
                Response.BulkTransaction response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

    }
}
