// DO NOT EDIT: File is generated by code generator.
using System;
using System.Net;
using System.Net.Http;
using NUnit.Framework;
using System.Threading.Tasks;
using System.Collections.Generic;

using PokepayPartnerCsharpSdk;

namespace PokepayPartnerCsharpSdk.Test
{
    public class TestGetPrivateMoneySummary
    {
        private Client client;

        [OneTimeSetUp]
        public void OneTimeSetup()
        {
            client = new Client("~/.pokepay/test-config.ini");
        }

        [Test]
        public async Task GetPrivateMoneySummary0()
        {
            try {
                Request.GetPrivateMoneySummary request = new Request.GetPrivateMoneySummary(
                    "b0ef9f12-9460-4bbe-a922-37c750bbcd01"
                );
                Response.PrivateMoneySummary response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task GetPrivateMoneySummary1()
        {
            try {
                Request.GetPrivateMoneySummary request = new Request.GetPrivateMoneySummary(
                    "b0ef9f12-9460-4bbe-a922-37c750bbcd01"
                ) {
                    To = "2023-05-17T04:25:38.000000Z",
                };
                Response.PrivateMoneySummary response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

        [Test]
        public async Task GetPrivateMoneySummary2()
        {
            try {
                Request.GetPrivateMoneySummary request = new Request.GetPrivateMoneySummary(
                    "b0ef9f12-9460-4bbe-a922-37c750bbcd01"
                ) {
                    From = "2022-12-18T18:44:19.000000Z",
                    To = "2022-01-12T23:51:33.000000Z",
                };
                Response.PrivateMoneySummary response = await request.Send(client);
                Assert.NotNull(response, "Shouldn't be null at least");
            } catch (HttpRequestException e) {
                Assert.AreNotEqual((int) e.Data["StatusCode"], (int) HttpStatusCode.BadRequest, "Shouldn't be BadRequest");
                Assert.True((int) e.Data["StatusCode"] >= 300, "Should be larger than 300");
            }
        }

    }
}
